keops:
  image: keops:latest
  container_name: keops
  restart: always
  environment: 
    - KEOPS_DB_NAME=keopsdb
    - KEOPS_DB_HOST=postgres_db
    - KEOPS_DB_USER=keopsdb
    - KEOPS_DB_PASS=.keopsdb.
    - KEOPS_DB_PORT=5432
  ports:
    - "8080:80"
  links:
    - postgres_db
    
postgres_db:
  image: postgres:9.5-alpine
  container_name: postgres_db 
  restart: always
  environment:
    - POSTGRES_PASSWORD=.keopsdb.
