version: '2'

services:
  keops:
    build:
      context: .
      dockerfile: Dockerfile
    image: keops:latest
    container_name: keops
    restart: always
    environment: 
      - KEOPS_DB_NAME=keopsdb
      - KEOPS_DB_HOST=keopsdb
      - KEOPS_DB_USER=keopsdb
      - KEOPS_DB_PASS=PASSWORD_FOR_USER_KEOPS
      - KEOPS_DB_PORT=5432
    ports:
      - "8080:80"
    depends_on:
      - keopsdb
    networks:
      - keops
      
  keopsdb:
    build:
      context: .
      dockerfile: Dockerfile-db
    image: keopsdb:latest
    container_name: keopsdb
    networks:
      - keops
    environment:
      - POSTGRESPASSWORD=PASSWORD_FOR_POSTGRES
      - KEOPS_ROOT_PASSWORD_HASH=$$2y$$10$$8i3XnbB4xQA7pRsM5D2gsukeZeVWlSsFaDWuA5o3wQ0tjqRMHIe0C

networks:
  keops: